### PR TITLE
Upgrade dependencies, and more importantly, stop depending on internal Guice classes

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by JessThrysoee** [comment]
:+1:

**Comment by pswvg** [comment]
+1

**Comment by manzke** [comment]
hey guys let me check it with @simonetripodi

**Comment by simonetripodi** [comment]
sorry for the late reaction and thanks @manzke for the ping!
@benmccann @JessThrysoee @pswvg I just cut Rocoto 6.3 release, let's just wait for Maven central repo sync before updating your poms :)
Thanks for the contribution!

**Pull request merged**
